---
# This task updates and upgrades the remote.
# name - define name of task.
# become - we need sudo privileges, so we set for this field value "yes".
# apt - uses the apt command on the remote to install packages.

- name: Updating & Upgrading Remote
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

# Installs Syslog-NG to collect the system logs.

- name: Installing Syslog-NG
  become: yes
  apt:
    name: 
      - syslog-ng

# These steps will get rid of the /etc/syslog-ng-syslog-ng.conf file. Then a file with the client information will be copied from the server to the client and the IP will be changed so the syslogs can be sent to the collector server.

- name: Delete old syslog-ng file
  become: yes
  file: path=/etc/syslog-ng/syslog-ng.conf state=absent

- name: Move new syslog file to the client
  become: yes
  copy: 
       src: ~/Ansible-Linux-Opgaven/syslog-ng.conf
       dest: /etc/syslog-ng/syslog-ng.conf

# The tty10.conf file is needed for the sending of the data. Since it might exist it will first try to be deleted, then it will copy a new version over from the Ansible root.

- name: Delete old tty10.conf file
  become: yes
  file: path=/usr/share/syslog-ng/include/scl/system/tty10.conf state=absent

- name: Move new tty10.conf file to the client
  become: yes
  copy: 
       src: ~/Ansible-Linux-Opgaven/tty10.conf
       dest: /usr/share/syslog-ng/include/scl/system/tty10.conf

